### ISSUE TITLE
Getting Fail to Fetch error

### ISSUE THREAD

**Issue by jbrinkman** [auth0-community/auth0-chrome-sample#11]
I am trying to work through the Auth0-Chrome extension example, but no matter what I do, I am getting a "Failed to Fetch" error.  I suspect there is something wrong with user profile access, but I am not sure what and I don't seem to be able to attach the debugger to main.js in the example.  In looking through the authenticate method, it is just returning a generic error so I can't really see what the problem is.

**Comment by jbrinkman** [comment]
After finally digging through docs on debugging the background code, I found that there was a a CORS error occurring.

```
Failed to load https://{AUTH0_DOMAIN}/oauth/token: Response to preflight request doesn't 
pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested 
resource. Origin 'chrome-extension://{extension_id}' is therefore not 
allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to 
fetch the resource with CORS disabled.
```
Further research indicates that the chrome extension manifest should include a permissions line in the manifest for the {AUTH0_DOMAIN}. See: [Cross-Origin XMLHttpRequest ](https://developer.chrome.com/extensions/xhr) in the Chrome Extension documentation.

**Comment by jrnt30** [comment]
Thanks, was having the same issue!

**Comment by penseeartificielle** [comment]
Hi, sorry to ask but I can't make this extension work... I've done the CORS fixme, and when I try to connect it says "Login failed" with a 401.
I tried to debug and apparently when I send the challenge to the server it outputs a "fail". Can you share a bit of your configuration ? 

1) do you use scope: 'openid profile offline_access' ?
2) main.js .authenticate(options) returns an exception here : PKCEClient.js line 38 const result = await fetch(`https://${domain}/oauth/token`, { 401
3) in Auth0 logs it says Type | Failed Exchange - Description | Unauthorized

Really thanks in advance for your help !

**Comment by PucheuMickael** [comment]
Hello there,

In order to make the Auth0 Chrome extensions working ( with Chrome Extension ), you have to set the Application type to Native.

Dashboard -> Applications -> Your App -> Application Type

Found the solution there ( last comment )
https://github.com/auth0/react-native-auth0/issues/62

**Comment by markon1** [comment]
> Hello there,
> 
> In order to make the Auth0 Chrome extensions working ( with Chrome Extension ), you have to set the Application type to Native.
> 
> Dashboard -> Applications -> Your App -> Application Type
> 
> Found the solution there ( last comment )
> [auth0/react-native-auth0#62](https://github.com/auth0/react-native-auth0/issues/62)

This saved me after few hours of debugging.
Should definitely be added to https://auth0.com/docs/quickstart/native/chrome/01-login

**Comment by beardaway** [comment]
Thanks a lot for all the feedback! i just passed it to appropriate team responsible for that doc!
